2020-01-26 03:05:40,814 ERROR: Exception on /api/tokens [POST] [in C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask_httpauth.py", line 105, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\api\tokens.py", line 10, in get_token
    token = g.current_user.get_token()
AttributeError: 'User' object has no attribute 'get_token'
2020-01-26 03:07:30,727 ERROR: Exception on /api/tokens [POST] [in C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask_httpauth.py", line 105, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\api\tokens.py", line 10, in get_token
    token = g.current_user.get_token()
AttributeError: 'User' object has no attribute 'get_token'
2020-01-26 03:09:41,572 ERROR: Exception on /api/tokens [POST] [in C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask_httpauth.py", line 105, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\api\tokens.py", line 10, in get_token
    token = g.current_user.get_token()
AttributeError: 'User' object has no attribute 'get_token'
2020-01-26 03:09:47,497 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:84]
